#if !canImport(ObjectiveC)
import XCTest

extension ImportTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImportTests = [
        ("testSignAndVerify", testSignAndVerify),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ImportTests.__allTests__ImportTests),
    ]
}
#endif
